apiVersion: apps/v1
kind: Deployment
metadata:
  name: substrate-alice
spec:
  selector:
    matchLabels:
      app: substrate-alice
  replicas: 1
  template:
    metadata:
      labels:
        app: substrate-alice
    spec:
      containers:
      - name: alice-substrate
        image: "chevdor/substrate"
        command: ["/bin/sh","-c"]
        args: 
        - "substrate"
        - "--base-path /tmp/alice"
        - "--alice"
        - "--port 30333"
        - "--ws-port 9944"
        - "--rpc-port 9933"
        - "--telemetry-url ws://telementry:8000/submit"
        ports:
        - name: port
          containerPort: 30333
        - name: ws-port
          containerPort: 9944
        - name: rpc-port
          containerPort: 9933
---
apiVersion: v1
kind: Service
metadata:
  name: substrate-alice
spec:
  ports:
  - name: port-1
    port: 30333
    protocol: TCP
    targetPort: 30333
  - name: port-2
    port: 9944
    protocol: TCP
    targetPort: 9944
  - name: port-3
    port: 9933
    protocol: TCP
    targetPort: 9933
  selector:
    app: substrate-alice